ModuleName: Plugin.Microsoft.Azure.SignalR.Benchmark.SignalRBenchmarkPlugin, Plugin.Microsoft.Azure.SignalR.Benchmark
Pipeline:
- - Method: InitStatisticsCollector
    Parameter.LatencyStep: 100
    Parameter.LatencyMax: 1000
    Type: echo
- - Method: CollectStatistics
    Parameter.Interval: 1000
    Parameter.StatisticsOutputPath: haha.txt
    Type: echo
- - Method: CreateConnection
    Parameter.ConnectionTotal: 500
    Parameter.HubUrl: http://localhost:5050/signalrbench
    Parameter.Protocol: json
    Parameter.TransportType: Websockets
    Type: echo
- - Method: StartConnection
    Parameter.ConcurrentConnetion: 2
    Type: echo

- - Method: RegisterCallbackRecordLatency
    Type: echo


- - Method: Echo
    Parameter.Duration: 5000
    Parameter.ConnectionTotal: 500
    Parameter.Interval: 1000
    Parameter.MessageSize: 2048
    Parameter.Modulo: 500
    Parameter.RemainderBegin: 0
    Parameter.RemainderEnd: 100
    Type: echo

- - Method: Wait
    Parameter.Duration: 5000
    Type: echo
- - Method: StopCollector
    Type: echo
- - Method: StopConnection
    Type: echo
- - Method: DisposeConnection
    Type: echo
Types: [echo]
