- name: Setup alternate SSH port
  hosts: linux
  user: "{{ansible_ssh_user}}"
  become: true
  become_user: root
  become_method: sudo
  tasks:
    - block:
      - name: "Change sshd port to 22222"
        lineinfile:
          dest: "/etc/ssh/sshd_config"
          regexp: "^Port"
          line: "Port 22222"
      #  notify: "Restart sshd"
      #- name: "Restart sshd"
      #  service:
      #    name: sshd
      #    state: restarted
