ModuleName: Plugin.Microsoft.Azure.SignalR.Benchmark.SignalRBenchmarkPlugin, Plugin.Microsoft.Azure.SignalR.Benchmark

Types:
- P1
- P2

Pipeline:
# first step
-
  - Type: P1
    Method: CreateConnection
    Parameter.ConnectionTotal: 1000
    Parameter.HubUrl: http://localhost:5000/signalrbench
    Parameter.Protocol: json
    Parameter.TransportType: WebSockets
  # - Type: P2
  #   Method: Create
  #   Parameter.ConnectionTotal: 999
  #   Parameter.Idle: 200