kind: Pod
apiVersion: v1
metadata:
  name: mypod25
  labels:
     app: portal1
spec:
  containers:
  - name: mypod25
    image: signalrbenchmark/perf:1.3
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi
    volumeMounts:
    - mountPath: "/mnt/azure"
      name: volume
    command: ["/bin/sh","-c"]
    args: ["cd /mnt/azure; unzip portal.zip -d ./portal7 && echo hi >>test && sleep 100000"]
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: my-azurefile12