kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: my-azurefile13
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
parameters:
 storageAccount: biqianperfsa