apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prometheus
  labels:
    type: metrics-azurefile
spec:
  capacity:
    storage: 60Gi
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: azure-secret
    shareName: prometheus
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: Namespace
metadata:
  name: prometheus


