apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portal-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  tls:
    - hosts:
        - PORTAL_DOMAIN_PLACE_HOLDER
      secretName: perf-cert
  rules:
    - host: PORTAL_DOMAIN_PLACE_HOLDER
      http:
        paths:
          - backend:
              service:  
                name: portal
                port: 
                  number: 80
            path: /upstream/validate
            pathType: Prefix
          - backend:
              service: 
                name: portal
                port: 
                  number: 80
            path: /
            pathType: Prefix