apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: perfdashboard
subjects:
- kind: ServiceAccount
  name: perfdashboard
  namespace: default
roleRef:
  kind: ClusterRole
  name: perfdashboard
  apiGroup: rbac.authorization.k8s.io