apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: coordinator
spec:
  selector:
    matchLabels:
      app: coordinator
  replicas: 1 
  template:
    metadata:
      labels:
        app: coordinator
    spec:
      nodeSelector:
        agentpool: captain
      containers:
        - name: coordinator
          image: signalrbenchmark/perf:1.4.4
          resources:
            requests:
              cpu: 1000m
              memory: 1024Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
          volumeMounts:
            - mountPath: "/mnt/perf"
              name: volume
          command: ["/bin/sh", "-c"]
          args: ["cp /mnt/perf/manifest/Coordinator/Coordinator.zip /home ; cd /home ; unzip Coordinator.zip ;exec ./Coordinator;"]
          env:
            - name: kvUrl
              value: KVURL_PLACE_HOLDER
            - name: PodName
              valueFrom:
                fieldRef:
                   fieldPath: metadata.name
            - name: redis
              value: redis-master
            - name: msiAppId
              value: MSI_PLACE_HOLDER
            - name: storage
              value: STORAGE_PLACE_HOLDER
            - name: domain
              value: DOMAIN_PLACE_HOLDER
      volumes:
        - name: volume
          azureFile:
            secretName: azure-secret
            shareName: perf
            readOnly: false
