<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>Azure.SignalRBench.Common</RootNamespace>
    <langversion>8</langversion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Data.Tables" Version="12.10.0" />
    <PackageReference Include="Azure.Identity" Version="1.13.1" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.4.4" />
    <PackageReference Include="Azure.Storage.Queues" Version="12.20.1" />
    <PackageReference Include="Microsoft.AspNetCore.WebUtilities" Version="2.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="3.1.7" />
    <PackageReference Include="Azure.Security.KeyVault.Secrets" Version="4.0.3" />
    <PackageReference Include="Azure.Storage.Files.Shares" Version="12.2.3" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
    <PackageReference Include="System.Linq.Async" Version="4.1.1" />
    <PackageReference Include="System.Net.NameResolution" Version="4.3.0" />
    <PackageReference Include="StackExchange.Redis" Version="2.1.58" />
  </ItemGroup>

</Project>
