apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: portal
spec:
  selector:
    matchLabels:
      app: portal
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: portal
    spec:
      serviceAccountName: perfdashboard
      nodeSelector:
        agentpool: captain
      containers:
        - name: portal
          image: signalrbenchmark/perf:1.4.4
          resources:
            requests:
              cpu: 1000m
              memory: 1024Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
          volumeMounts:
            - mountPath: "/mnt/perf"
              name: volume
          command: ["/bin/sh", "-c"]
          args: ["cp /mnt/perf/manifest/Portal/Portal.zip /home ; cd /home ; unzip Portal.zip ; exec ./Portal"]
          env:
            - name: kvUrl
              value: KVURL_PLACE_HOLDER
            - name: msiAppId
              value: MSI_PLACE_HOLDER
      volumes:
        - name: volume
          azureFile:
            secretName: azure-secret
            shareName: perf
            readOnly: false
